# Site
name: D4 Project
description: Large-scale distributed sensor network project to monitor DDoS and malicious activities
meta_description: "Large-scale distributed sensor network project to monitor DDoS and malicious activities"
logo: 'assets/images/logo.png'
favicon: 'assets/favicon/favicon.ico'
paginate: 12
baseurl:
email: 'info@circl.lu'
#google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  CIRCL:
    name: CIRCL
    display_name: circl
#    gravatar: e56154546cf4be74e393c62d1ae9f9d4
#    email: wowthemesnet@gmail.com
    web: https://www.circl.lu/
    twitter: https://twitter.com/d4_project
    description: "Computer Incident Response Center Luxembourg (CIRCL)"
  alexis:
    name: Alexis Lecocq
    display_name: Alexis Lecocq
    gravatar: 9e20e0afa2f69dd5b61eb3e9cc88ecac
    web: https://be.linkedin.com/in/lecocqalexis
#  john:
#    name: John
#    display_name: John
#    gravatar: b1cc14991db7a456fcd761680bbc8f81
#    email: wowthemesnet@gmail.com
#    web: https://www.wowthemes.net/category/jekyll-themes/
#    twitter: https://twitter.com/wowthemesnet
#    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
- jekyll-paginate
- jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Other
markdown: kramdown
highlighter: rouge
